backend:
  name: github
  repo: BozidarVukovic/het-teamkompas
  branch: main
  auth_type: implicit
  app_id: Ov23liDoa9x35Ne3SMES

locale: nl

media_folder: public/blog/images
public_folder: /blog/images

collections:
  - name: blog
    label: Blogartikel
    label_singular: Artikel
    folder: src/content/blog
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Titel, name: title, widget: string }
      - { label: Publicatiedatum, name: date, widget: datetime, format: "YYYY-MM-DD", date_format: "DD-MM-YYYY", time_format: false }
      - { label: Samenvatting, name: description, widget: text, hint: "Korte beschrijving voor Google (max 160 tekens)" }
      - { label: Afbeelding, name: image, widget: image, required: false }
      - { label: Inhoud, name: body, widget: markdown }
