import { useEffect, useMemo, useState } from "react";
import { Helmet } from "react-helmet-async";
import { getFunctions, httpsCallable } from "firebase/functions";
import { useParams } from "react-router-dom";
import { FREE_SCAN_QUESTIONS, FREE_SCAN_SCALE, FREE_SCAN_THEMES, FREE_SCAN_VERSION } from "../../data/freeScanConfig";
import { calculateFreeScanResults } from "../../lib/freeScanScoring";
import "../../styles/free-scan.css";

const STORAGE_KEY = `teamkompas-gratis-scan-${FREE_SCAN_VERSION}`;
const emit = (name, data={}) => window.dispatchEvent(new CustomEvent("teamkompas:analytics", { detail:{ name, ...data } }));

// De server rekent de scores en is daarin leidend, maar stuurt geen kleuren mee.
// We halen de themakleur daarom hier uit de lokale configuratie, anders blijven
// de balken onzichtbaar (background: undefined).
const themeColor = (id) => FREE_SCAN_THEMES.find((t) => t.id === id)?.color || "var(--tk-color-teal)";

function ScoreOverview({ result }) {
  return <div className="free-score-list" aria-label="Themascores">{result.themeScores.map(theme=><div className="free-score" key={theme.id}><div><strong>{theme.label}</strong><span>{theme.zone?.label || "Geen score"}</span></div><div className="free-score-track"><i role="img" aria-label={`${theme.label}: ${theme.score ?? "geen"} van 100`} style={{width:`${theme.score || 0}%`,background:themeColor(theme.id)}} /></div><b>{theme.score ?? "–"}</b></div>)}</div>;
}

export function GratisTeamscanReport() {
  const { token } = useParams(); const [state,setState]=useState({loading:true});
  useEffect(()=>{ httpsCallable(getFunctions(),"getFreeScanReport")({token}).then(r=>setState({report:r.data})).catch(()=>setState({error:"Deze rapportlink is ongeldig of verlopen."})); },[token]);
  if(state.loading) return <main className="free-shell"><p>Rapport laden…</p></main>;
  if(state.error) return <main className="free-shell"><Helmet><meta name="robots" content="noindex,nofollow" /></Helmet><h1>Rapport niet beschikbaar</h1><p>{state.error}</p></main>;
  const {participant,result,completedAt}=state.report;
  return <main className="free-shell free-report"><Helmet><title>Jouw persoonlijke Teamkompas</title><meta name="robots" content="noindex,nofollow" /></Helmet><header><span>Luisteren · Meten · Bewegen</span><h1>Jouw persoonlijke Teamkompas</h1><p>{participant.firstName} · {new Date(completedAt).toLocaleDateString("nl-NL")}</p></header><section><h2>Jouw persoonlijke perspectief</h2><p>Deze uitslag weerspiegelt hoe jij de samenwerking ervaart. Het is geen oordeel of diagnose van het volledige team. Verschillen in beleving kunnen juist waardevolle gespreksinformatie opleveren.</p><ScoreOverview result={result}/></section><section><h2>Samenvatting</h2><p><strong>Kracht:</strong> {result.strengths[0]?.label}.</p><p><strong>Ontwikkelkans:</strong> {result.opportunities[0]?.label}.</p>{result.patterns.map(p=><article key={p.id}><h3>{p.title}</h3><p>{p.text}</p></article>)}</section><section><h2>Van inzicht naar beweging</h2>{result.themeScores.map(t=><article className="free-theme" key={t.id}><h3>{t.label} — {t.score}/100</h3><p>{t.description} Jouw antwoorden wijzen op een <strong>{t.zone.label.toLowerCase()}</strong>. Dit kan waardevol zijn om samen verder te onderzoeken.</p><p><strong>Reflectie:</strong> {t.reflection}</p><p><strong>Klein experiment:</strong> {t.experiment}</p></article>)}</section><section className="free-cta"><h2>Van één perspectief naar een teambeeld</h2><p>De volledige Teamscan maakt overeenkomsten, verschillen en onderliggende patronen tussen teamleden zichtbaar.</p><a className="tk-button tk-button-primary" href="/teamscan" onClick={()=>emit("free_scan_report_full_scan_click")}>Ontdek de volledige Teamscan</a></section></main>;
}

export default function GratisTeamscan() {
  const saved=useMemo(()=>{try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||{}}catch{return{}}},[]);
  const [phase,setPhase]=useState(saved.phase||"landing"), [index,setIndex]=useState(saved.index||0), [answers,setAnswers]=useState(saved.answers||{}), [sessionId,setSessionId]=useState(saved.sessionId||"");
  const [person,setPerson]=useState({firstName:"",email:"",role:"",organisation:"",teamSize:"",consentProcessing:false,consentMarketing:false,hp:""}); const [busy,setBusy]=useState(false),[error,setError]=useState(""),[outcome,setOutcome]=useState(null);
  useEffect(()=>{if(phase==="scan") localStorage.setItem(STORAGE_KEY,JSON.stringify({phase,index,answers,sessionId}));},[phase,index,answers,sessionId]);
  useEffect(()=>{emit("free_scan_page_view")},[]);
  async function start(){setError("");setBusy(true);try{const r=await httpsCallable(getFunctions(),"startFreeScan")({source:document.referrer||"direct",utm:Object.fromEntries(new URLSearchParams(location.search))});setSessionId(r.data.sessionId);setPhase("scan");emit("free_scan_started")}catch{setError("Starten lukt nu niet. Probeer het over een moment opnieuw.")}finally{setBusy(false)}}
  function choose(value){setAnswers(a=>({...a,[FREE_SCAN_QUESTIONS[index].id]:value}));}
  function next(){if(!answers[FREE_SCAN_QUESTIONS[index].id])return setError("Kies eerst het antwoord dat het beste past.");setError("");if(index===FREE_SCAN_QUESTIONS.length-1)setPhase("details");else{const ni=index+1;setIndex(ni);[6,12,18].includes(ni)&&emit("free_scan_progress",{percent:Math.round(ni/24*100)})}}
  async function finish(e){e.preventDefault();setError("");if(!person.consentProcessing)return setError("Toestemming voor het rapport is nodig om af te ronden.");setBusy(true);try{const local=calculateFreeScanResults(answers);const r=await httpsCallable(getFunctions(),"completeFreeScan")({sessionId,answers,participant:person,questionnaireVersion:FREE_SCAN_VERSION});setOutcome({...local,...r.data.result,reportUrl:r.data.reportUrl,emailStatus:r.data.emailStatus});localStorage.removeItem(STORAGE_KEY);setPhase("result");emit("free_scan_completed")}catch(err){setError(err?.message||"Opslaan of verzenden is niet gelukt. Je antwoorden blijven op dit apparaat bewaard.")}finally{setBusy(false)}}
  const meta=<Helmet><title>Gratis teamscan | Mijn Teamkompas</title><meta name="description" content="Ontdek in 8 tot 10 minuten hoe jij de samenwerking in jouw team ervaart en ontvang direct jouw persoonlijke Teamkompas."/><link rel="canonical" href="https://www.mijnteamkompas.nl/gratis-teamscan"/><meta property="og:title" content="Gratis persoonlijke teamscan | Mijn Teamkompas"/></Helmet>;
  if(phase==="landing")return <main className="free-page">{meta}<section className="free-hero"><div><span className="free-eyebrow">Gratis individuele teamscan</span><h1>Ontdek hoe jij de samenwerking binnen jouw team ervaart</h1><p>Beantwoord 24 vragen over veiligheid, communicatie, eigenaarschap, verbinding, energie en leiderschap. Je krijgt direct inzicht en een persoonlijk rapport.</p><ul><li>Gratis deelname</li><li>8–10 minuten</li><li>Persoonlijk en vertrouwelijk</li><li>Direct inzicht</li></ul><button className="tk-button tk-button-primary" disabled={busy} onClick={start}>{busy?"Even geduld…":"Start de gratis teamscan"}</button>{error&&<p role="alert" className="free-error">{error}</p>}</div><aside><b>Jouw perspectief staat centraal</b><p>De uitkomst is geen oordeel over het hele team. Je herkent sterke punten, mogelijke patronen en een concrete eerste beweging.</p></aside></section><section className="free-content"><h2>Luisteren. Meten. Bewegen.</h2><div className="free-cards">{FREE_SCAN_THEMES.map(t=><article key={t.id}><i style={{background:t.color}}/><h3>{t.label}</h3><p>{t.description}</p></article>)}</div><div className="free-info"><article><h2>Wat ontvang je?</h2><p>Een directe samenvatting, een beveiligd persoonlijk webrapport, reflectievragen en kleine experimenten die je binnen één of twee weken kunt proberen.</p></article><article><h2>Hoe gaan we met gegevens om?</h2><p>We vragen pas na de vragen om je voornaam en e-mailadres. Verwerking voor het rapport en commerciële communicatie hebben aparte, niet vooraf aangevinkte toestemmingen. Lees onze <a href="/privacyverklaring_mijnteamkompas.pdf">privacyverklaring</a>.</p></article></div><details><summary>Wat is het verschil met de volledige Teamscan?</summary><p>Deze gratis scan toont één persoonlijke beleving. De volledige scan vergelijkt veilig de perspectieven van meerdere teamleden en vormt een basis voor het teamgesprek.</p></details><button className="tk-button tk-button-primary" onClick={start}>Start mijn scan</button></section></main>;
  if(phase==="scan"){const question=FREE_SCAN_QUESTIONS[index];return <main className="free-shell">{meta}<Helmet><meta name="robots" content="noindex,nofollow"/></Helmet><div className="free-progress"><span>Vraag {index+1} van {FREE_SCAN_QUESTIONS.length}</span><progress max={FREE_SCAN_QUESTIONS.length} value={index+1}/></div><section className="free-question"><span>{FREE_SCAN_THEMES.find(t=>t.id===question.theme).label}</span><h1>{question.text}</h1><fieldset><legend className="sr-only">Kies één antwoord</legend>{FREE_SCAN_SCALE.map(o=><label key={o.value} className={answers[question.id]===o.value?"selected":""}><input type="radio" name={question.id} checked={answers[question.id]===o.value} onChange={()=>choose(o.value)}/><b>{o.value}</b>{o.label}</label>)}</fieldset>{error&&<p role="alert" className="free-error">{error}</p>}<div className="free-actions"><button disabled={index===0} onClick={()=>setIndex(i=>i-1)}>Terug</button><button className="tk-button tk-button-primary" onClick={next}>{index===23?"Naar jouw rapport":"Volgende"}</button></div></section></main>}
  if(phase==="details")return <main className="free-shell"><Helmet><meta name="robots" content="noindex,nofollow"/></Helmet><form className="free-form" onSubmit={finish}><span className="free-eyebrow">Je bent er bijna</span><h1>Nog een paar gegevens en je uitslag staat klaar</h1><p>We vragen alleen wat nodig is. Organisatie, rol en teamgrootte zijn optioneel.</p><label>Voornaam *<input required value={person.firstName} onChange={e=>setPerson({...person,firstName:e.target.value})}/></label><label>E-mailadres *<input required type="email" value={person.email} onChange={e=>setPerson({...person,email:e.target.value})}/></label><div className="free-form-grid"><label>Organisatie<input value={person.organisation} onChange={e=>setPerson({...person,organisation:e.target.value})}/></label><label>Functierol<input value={person.role} onChange={e=>setPerson({...person,role:e.target.value})}/></label></div><input className="free-hp" tabIndex="-1" autoComplete="off" value={person.hp} onChange={e=>setPerson({...person,hp:e.target.value})}/><label className="free-check"><input type="checkbox" checked={person.consentProcessing} onChange={e=>setPerson({...person,consentProcessing:e.target.checked})}/> Ik geef toestemming om mijn antwoorden te verwerken, mijn rapport tijdelijk op te slaan zodat ik het kan bekijken. *</label><label className="free-check"><input type="checkbox" checked={person.consentMarketing} onChange={e=>setPerson({...person,consentMarketing:e.target.checked})}/> Ik ontvang graag af en toe inspiratie van Mijn Teamkompas (optioneel).</label>{error&&<p role="alert" className="free-error">{error}</p>}<div className="free-actions"><button type="button" onClick={()=>setPhase("scan")}>Terug</button><button className="tk-button tk-button-primary" disabled={busy}>{busy?"Rapport wordt gemaakt…":"Bekijk mijn uitslag"}</button></div></form></main>;
  return <main className="free-shell free-result"><Helmet><meta name="robots" content="noindex,nofollow"/></Helmet><span className="free-eyebrow">Dank je wel</span><h1>Dit is jouw persoonlijke Teamkompas</h1><p>Dit beeld weerspiegelt jouw beleving en is geen oordeel over het hele team.</p><ScoreOverview result={outcome}/><div className="free-cards"><article><h2>Jouw sterke basis</h2><ul className="free-theme-list">{outcome.strengths.map(x=><li key={x.id}><span style={{background:themeColor(x.id)}} aria-hidden="true" />{x.label}<b>{x.score}</b></li>)}</ul></article><article><h2>Ontwikkelkans</h2><ul className="free-theme-list">{outcome.opportunities.map(x=><li key={x.id}><span style={{background:themeColor(x.id)}} aria-hidden="true" />{x.label}<b>{x.score}</b></li>)}</ul></article></div><blockquote>{outcome.reflections[0]}</blockquote><p><strong>Probeer deze week:</strong> {outcome.experiments[0]}</p><p className="free-notice">{outcome.emailStatus==="sent"?"Je uitgebreide rapport is per e-mail verzonden.":"Je rapport staat klaar. Open het via onderstaande knop en bewaar de link goed."}</p><div className="free-actions"><a className="tk-button tk-button-primary" href={outcome.reportUrl}>Open volledig rapport</a><a className="tk-button tk-button-secondary" href="/teamscan" onClick={()=>emit("free_scan_result_full_scan_click")}>Ontdek de volledige Teamscan</a></div></main>;
}
