import { useEffect, useMemo, useState } from "react";
import { collection, getDocs, orderBy, query } from "firebase/firestore";
import { getFunctions, httpsCallable } from "firebase/functions";
import { db } from "../../lib/firebase";
import { ADM } from "../../styles/tokens";

const cell={padding:"11px 10px",borderBottom:`1px solid ${ADM.border}`,textAlign:"left",fontSize:13};
export default function PageGratisTeamscan(){
  const [items,setItems]=useState([]),[search,setSearch]=useState(""),[status,setStatus]=useState(""),[selected,setSelected]=useState(null),[error,setError]=useState("");
  async function load(){try{const snap=await getDocs(query(collection(db,"freeScanInstances"),orderBy("startedAt","desc")));setItems(snap.docs.map(d=>({id:d.id,...d.data()})))}catch(e){setError("De inzendingen konden niet worden geladen.")}}
  useEffect(()=>{load()},[]);
  const filtered=useMemo(()=>items.filter(i=>!status||i.status===status).filter(i=>`${i.participant?.firstName||""} ${i.participant?.email||""} ${i.participant?.organisation||""}`.toLowerCase().includes(search.toLowerCase())),[items,search,status]);
  const completed=items.filter(i=>i.completedAt).length, sent=items.filter(i=>i.email?.status==="sent").length, failed=items.filter(i=>i.email?.status==="failed").length;
  async function action(id,action){if(!confirm(action==="delete"?"Deze inzending definitief verwijderen?":"Persoonsgegevens en antwoorden anonimiseren?"))return;try{await httpsCallable(getFunctions(),"manageFreeScan")({id,action});setSelected(null);load()}catch{setError("De beheeractie is mislukt.")}}
  function exportCsv(list=filtered){const rows=[["gestart","afgerond","status","voornaam","email","organisatie","rol","marketing","sterkte","ontwikkelkans"],...list.map(i=>[i.startedAt?.toDate?.().toISOString()||"",i.completedAt?.toDate?.().toISOString()||"",i.status,i.participant?.firstName||"",i.participant?.email||"",i.participant?.organisation||"",i.participant?.role||"",i.consents?.marketing?.granted?"ja":"nee",i.result?.strengths?.[0]?.label||"",i.result?.opportunities?.[0]?.label||""])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="gratis-teamscan.csv";a.click()}
  if(selected)return <div><button onClick={()=>setSelected(null)}>← Terug</button><h2>{selected.participant?.firstName||"Gestarte scan"}</h2><p>{selected.participant?.email} · {selected.participant?.organisation} · {selected.status}</p><h3>Scores</h3>{selected.result?.themeScores?.map(t=><p key={t.id}>{t.label}: <strong>{t.score}/100</strong> — {t.zone?.label}</p>)}<h3>Patronen</h3>{selected.result?.patterns?.map(p=><p key={p.id}><strong>{p.title}</strong>: {p.text}</p>)}<h3>Antwoorden</h3><pre style={{whiteSpace:"pre-wrap",background:ADM.navy,padding:16,borderRadius:10}}>{JSON.stringify(selected.answers||{},null,2)}</pre><p>Vragenlijst {selected.questionnaireVersion} · scoremodel {selected.scoreModelVersion}</p>{selected.reportToken&&<a href={`/gratis-teamscan/rapport/${selected.reportToken}`} target="_blank" rel="noreferrer" style={{color:ADM.teal}}>Rapport bekijken</a>}<div style={{display:"flex",gap:10,marginTop:22}}><button onClick={()=>action(selected.id,"anonymize")}>Anonimiseren</button><button onClick={()=>action(selected.id,"delete")} style={{color:ADM.red}}>Verwijderen</button></div></div>;
  return <div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:12}}>{[["Gestart",items.length],["Afgerond",completed],["Conversie",items.length?`${Math.round(completed/items.length*100)}%`:"–"],["E-mail verzonden",sent],["Verzendfouten",failed]].map(([l,v])=><div key={l} style={{background:ADM.navy,padding:18,borderRadius:12}}><small>{l}</small><div style={{fontSize:26,fontWeight:800}}>{v}</div></div>)}</div><div style={{display:"flex",gap:10,margin:"24px 0",flexWrap:"wrap"}}><input placeholder="Zoek e-mail, naam of organisatie" value={search} onChange={e=>setSearch(e.target.value)} style={{minWidth:280,padding:10}}/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Alle statussen</option>{["started","report_generated","email_sent","email_failed","anonymized"].map(s=><option key={s}>{s}</option>)}</select><button onClick={()=>exportCsv()}>Exporteer CSV</button></div>{error&&<p style={{color:ADM.red}}>{error}</p>}<div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr>{["Gestart","Deelnemer","Organisatie","Status","Sterkte","Ontwikkelkans","Marketing"].map(h=><th key={h} style={cell}>{h}</th>)}</tr></thead><tbody>{filtered.map(i=><tr key={i.id} onClick={()=>setSelected(i)} style={{cursor:"pointer"}}><td style={cell}>{i.startedAt?.toDate?.().toLocaleString("nl-NL")||"–"}</td><td style={cell}>{i.participant?.firstName||"Nog anoniem"}<br/><small>{i.participant?.email}</small></td><td style={cell}>{i.participant?.organisation||"–"}</td><td style={cell}>{i.status}</td><td style={cell}>{i.result?.strengths?.[0]?.label||"–"}</td><td style={cell}>{i.result?.opportunities?.[0]?.label||"–"}</td><td style={cell}>{i.consents?.marketing?.granted?"Ja":"Nee"}</td></tr>)}</tbody></table></div></div>;
}
